Update power

diff --git a/scripts/power b/scripts/power
--- a/scripts/power
+++ b/scripts/power
@@ -29,7 +29,13 @@ case $CHOICE in
         ;;
 
     2)
-        sudo pacman -Syu && sudo reboot
+        if [ -x "$(command -v apt)" ];	     then sudo apt update && sudo apt upgrade
+		elif [ -x "$(command -v dnf)" ];     then sudo dnf upgrade
+		elif [ -x "$(command -v yum)" ];     then sudo yum update && sudo yum upgrade
+		elif [ -x "$(command -v zypper)" ];  then sudo zypper ref && sudo zypper up
+		elif [ -x "$(command -v pacman)" ];  then sudo pacman -Syu
+		else echo "FAILED TO UPDATE PACKAGES">&2; fi
+    	sudo reboot
     	;;
 
     3)
@@ -37,7 +43,13 @@ case $CHOICE in
     	;;
     
     4)
-        sudo pacman -Syu && sudo poweroff
+        if [ -x "$(command -v apt)" ];	     then sudo apt update && sudo apt upgrade
+		elif [ -x "$(command -v dnf)" ];     then sudo dnf upgrade
+		elif [ -x "$(command -v yum)" ];     then sudo yum update && sudo yum upgrade
+		elif [ -x "$(command -v zypper)" ];  then sudo zypper ref && sudo zypper up
+		elif [ -x "$(command -v pacman)" ];  then sudo pacman -Syu
+		else echo "FAILED TO UPDATE PACKAGES">&2; fi
+		sudo poweroff
     	;;
 
     5)
